# Generated by Django 6.0.2 on 2026-07-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('new_assignment', 'New Assignment'), ('submission_approved', 'Submission Approved'), ('deadline_reminder', 'Deadline Reminder'), ('assignment_overdue', 'Assignment Overdue'), ('new_submission', 'New Submission')], max_length=30),
        ),
    ]