# Generated by Django 6.0.2 on 2026-07-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('new_assignment', 'New Assignment'), ('submission_approved', 'Submission Approved'), ('submission_rejected', 'Submission Rejected'), ('deadline_reminder', 'Deadline Reminder'), ('assignment_overdue', 'Assignment Overdue'), ('new_submission', 'New Submission'), ('assignment_updated', 'Assignment Updated'), ('new_student_registered', 'New Student Registered'), ('new_teacher_registered', 'New Teacher Registered'), ('new_course_created', 'New Course Created'), ('contact_message', 'Contact Message'), ('course_assigned', 'Course Assigned'), ('student_left_course', 'Student Left Course'), ('student_removed_from_course', 'Student Removed From Course'), ('student_enrolled', 'Student Enrolled')], max_length=30),
        ),
    ]
