# Generated by Django 6.0.2 on 2026-07-11 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_teacher'),
        ('notifications', '0006_alter_notification_notif_type'),
        ('tasks', '0010_alter_assignment_due_date_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('notif_type', 'assignment_overdue')), fields=('task', 'notif_type'), name='unique_overdue_notification_per_task'),
        ),
    ]
