"""
Django settings for studyflow project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0_a3ny-w&ro7434pfr52e&4=2zknlkmpd_a^s=@nw%#skj5tgk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'drf_spectacular',

    'users',
    'courses',
    'tasks',
    'holidays',
    'analytics',
    'ml',
    'contact',
    'notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True  # Change later in production


ROOT_URLCONF = 'taskora.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taskora.wsgi.application'


import os

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# By default, uses PostgreSQL (matches the team's shared setup).
# To use SQLite locally instead (e.g. PostgreSQL not installed/working),
# set an environment variable before running manage.py:
#
#   Windows (PowerShell):  $env:USE_SQLITE="true"
#   Windows (cmd):         set USE_SQLITE=true
#   Mac/Linux:              export USE_SQLITE=true
#
# This only affects your local machine — do not commit this change
# or set it permanently, so the rest of the team keeps using PostgreSQL.

if os.environ.get('USE_SQLITE', '').lower() == 'true':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'taskora_db',
            'USER': 'taskora_user',
            'PASSWORD': 'admin123',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'users.backends.UsernameOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',  # keep as fallback
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        "rest_framework.authentication.SessionAuthentication", # allow admin session
        
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_RATES': {
        'otp_request': '5/hour',   # max 5 OTP sends/resends per email per hour
        'otp_verify':  '10/hour',  # max 10 verify attempts per email per hour
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'TaskOra API',
    'DESCRIPTION': 'API for the TaskOra student task management platform',
    'VERSION': '1.0.0',
}


# Email — Gmail SMTP
# EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'users.backends.IPv4EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
# EMAIL_HOST = '192.178.158.109'  # temporary diagnostic only, not a real fix
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = 'taskora2083@gmail.com'
EMAIL_HOST_PASSWORD = 'dnex lnin hypa fdwr'
DEFAULT_FROM_EMAIL  = 'TaskOra <taskora2083@gmail.com>'

# Contact form submissions are emailed to this address (the admin's Gmail).
ADMIN_NOTIFICATION_EMAIL = EMAIL_HOST_USER

import socket
socket.setdefaulttimeout(10)