# Generated by Django 6.0.2 on 2026-03-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(default=1.0)),
                ('priority', models.IntegerField(default=3)),
                ('task_type', models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam'), ('project', 'Project'), ('homework', 'Homework'), ('quiz', 'Quiz'), ('personal', 'Personal'), ('other', 'Other')], default='personal', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('priority_score', models.FloatField(default=0.0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('task_type', models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam'), ('project', 'Project'), ('homework', 'Homework'), ('quiz', 'Quiz'), ('other', 'Other')], default='assignment', max_length=20)),
                ('estimated_hours', models.FloatField(default=1.0)),
                ('priority', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
        ),
    ]
