# Generated by Django 6.0.2 on 2026-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_assignment_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='task_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam'), ('project', 'Project'), ('homework', 'Homework'), ('quiz', 'Quiz'), ('other', 'Other')], default='assignment', max_length=20),
        ),
    ]
