# Generated by Django 6.0.2 on 2026-06-02 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_assignment_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_student_assignment',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='task',
            name='submission_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='teacher_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.assignment'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('student', 'assignment'), name='unique_student_assignment'),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='course',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
