# Generated by Django 6.0.2 on 2026-07-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium-Low'), (3, 'Medium'), (4, 'Medium-High'), (5, 'High')], default=3),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='task_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam'), ('project', 'Project'), ('homework', 'Homework'), ('quiz', 'Quiz'), ('lab', 'Lab'), ('other', 'Other')], default='assignment', max_length=20),
        ),
    ]
