# Generated by Django 6.0.2 on 2026-07-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_assignment_priority_alter_assignment_task_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
