# Generated by Django 6.0.2 on 2026-07-17 07:40

import django.core.validators
import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_assignment_due_date_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), tasks.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), tasks.validators.validate_upload_size]),
        ),
    ]
