# Generated by Django 6.0.2 on 2026-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('festival', 'Festival'), ('optional', 'Optional')], default='public', max_length=20),
        ),
    ]
