# Generated by Django 6.0.2 on 2026-04-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_holiday_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='type',
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('public', 'Public'), ('festival', 'Festival'), ('regional', 'Regional')], default='public', max_length=20),
        ),
    ]
