# Generated by Django 6.0.2 on 2026-04-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_remove_holiday_type_holiday_holiday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('public', 'Public'), ('festival', 'Festival'), ('regional', 'Regional'), ('restricted', 'Restricted')], default='public', max_length=20),
        ),
    ]
