# Generated by Django 6.0.2 on 2026-07-05 16:26

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003 alter course teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='join_code',
            field=models.CharField(default=courses.models.generate_join_code, max_length=8, unique=True),
        ),
    ]
