# Generated by Django 6.0.2 on 2026-07-02 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    """
    Mark all users created before email verification was introduced
    as already verified so they don't get locked out.
    """
    User = apps.get_model('users', 'User')
    updated = User.objects.all().update(is_email_verified=True)
    print(f'\n  ✓ Marked {updated} existing user(s) as email-verified.')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Data migration — runs after schema changes
        migrations.RunPython(
            mark_existing_users_verified,
            reverse_code=migrations.RunPython.noop,  # no-op on rollback
        ),
    ]