# Generated by Django 6.0.2 on 2026-07-04 04:29

from django.db import migrations

def verify_existing_users(apps, schema_editor):
    User = apps.get_model('users', 'User')  # replace 'users' with your app label
    User.objects.filter(is_email_verified=False).update(is_email_verified=True)


def reverse_noop(apps, schema_editor):
    # Intentionally a no-op — we don't want a rollback to un-verify real users.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RunPython(verify_existing_users, reverse_noop),
    ]
